# Generated by Django 4.0.5 on 2022-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_description_alter_student_com_prom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='type',
            field=models.CharField(choices=[('TP', 'TP'), ('TD', 'TD'), ('INTERROGATION', 'INTERROGATION')], max_length=255, null=True),
        ),
    ]
