# Generated by Django 4.0.5 on 2022-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_homework_completed_homework_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='notice',
            field=models.TextField(blank=True),
        ),
    ]
