# Generated by Django 4.0.5 on 2022-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_homework_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
